server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8081
          predicates:
            - Path=/products/** 
        - id: reservation
          uri: http://localhost:8082
          predicates:
            - Path=/reservations/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path= /myPages/**
        - id: notice
          uri: http://localhost:8085
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://Product:8080
          predicates:
            - Path=/products/** 
        - id: reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: payment
          uri: http://Pay:8080
          predicates:
            - Path=/payments/** 
        - id: mypage
          uri: http://MaPage:8080
          predicates:
            - Path= /myPages/**
        - id: notice
          uri: http://Notice:8080
          predicates:
            - Path= 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
